[package]
name = "cv"
version = "0.1.0"
authors = ["CyberWolf37 <borel.loic.37@gmail.com>"]
edition = "2018"


[dependencies]
botMessenger = {git = "https://github.com/CyberWolf37/bot.git"}
log = "0.4.11"
env_logger = "0.8.1"